### ISSUE TITLE
Waiting for DevAlpha

### ISSUE THREAD

**Issue by rakeshtembhurne** [devalpha-io/devalpha-example#2]
When trying to run an example, it says Waiting for DevAlpha, and when https://devalpha.io/ is opened, it does nothing.

**Comment by fhqvst** [comment]
Hey Rakesh! We've just entered private beta, and so that's why you're not able to access the backtester. If you've submitted your email, then expect to receive a message in a few days on how to get started.

Feel free to reach out to me at filip [at] devalpha [dot] io or on here if you have any further questions.
